### ISSUE TITLE
Put V letter as changed in the image

### ISSUE THREAD

**Issue by kototama** [ColemakMods/mod-dh#1]
Hello,

While searching for optimal keyboard layout I found, almost randomly, your mod for Colemak and I'm very pleased to see your proposal. I'm on the verge of being convinced to learn it when I make the switch.

I have question regarding this [image](https://colemakmods.github.io/mod-dh/gfx/mod_dh_change_colemak.png). Wouldn't it be more honest to label the V key as modified since the D letter take its place?

**Comment by DreymaR** [comment]
Hi! ^_^

That's not my DH-mod (DbgHk), but SteveP's (DvbgHm). His is a bit more
radical.

I agree that it's a bit confusing with the V in that mod and whether one
may say it's moved or not. Technically, it hasn't moved but relative to ZXC
it has. I chose to keep ZXCV together in my mod, because this seems better
to me.

You can read more about this from the DreymaR's Big Bag topics on the
Colemak forum.

best,
Øystein "DreymaR"

**Comment by kototama** [comment]
I see. My misunderstanding comes from the ISO / ANSI keyboards differences. Thanks :)

**Comment by stevep99** [comment]
Yes, as I guess you realized, it comes down to the fact that the "[angle mod](http://colemakmods.github.io/ergonomic-mods/angle.html)" is being applied. 

Z, X, C are changed insofar as the physical key position changes, but of course you still type them with the same finger as with the traditional technique.   The V however stays on the same physical key (and same finger) as Colemak and Qwerty, so I consider it unchanged.
