### ISSUE TITLE
layout analyser for other languages

### ISSUE THREAD

**Issue by mkborregaard** [ColemakMods/mod-dh#10]
Is there an easy way to extend your layout analyser to work on other corpora, e.g. to get an impression of the most efficient layout for Danish text? Thanks!

**Comment by stevep99** [comment]
It's a good question, but unfortunately this is not supported currently. In principle though it would be possible to extend the functionality to allow it. What would be required is to allow the user to enter an alternative table of character and bigram frequencies.

**Comment by HughP** [comment]
@mkborregaard If you do get this working for another language please post, as I am interested in this too...  @stevep99 In a quick look through the code base here I don't see the code for the analyzer.

**Comment by stevep99** [comment]
Looking again at the code, it's certainly possible to support any language for which we have a full set of character and bigram frequency tables. This data might not be easy to come by though? 

Bu if any of you guys can provide it, I'd be happy to add support for this feature. 

See this file example frequency table for English:
http://colemakmods.github.io/mod-dh/webapp/resources/freq/books.freq

**Comment by mkborregaard** [comment]
There are monogram (http://practicalcryptography.com/media/cryptanalysis/files/danish_monograms.txt) , bigram (http://practicalcryptography.com/media/cryptanalysis/files/danish_bigrams.txt) and even trigram (practicalcryptography.com/media/cryptanalysis/files/danish_trigrams.txt.zip) tables for Danish here. I'm not completely certain how to calculate your third column - in the file you sent the frequency of all bigrams was 0, but I guess it is the frequency within-monogram and within-bigram?

**Comment by stevep99** [comment]
Those are _almost_ perfect (don't worry about the third column, it's just normalized so that frequencies add up to one). 

The only issue is the analyzer is designed to work with all the keys in the main section of the keyboard, which includes comma, full-stop, semicolon and slash, so we would ideally want frequencies (and bigrams) including those too!  

I hit the same issue when I tried to use [Peter Norvig's data](http://norvig.com/mayzner.html), which also covers only the alphabetic characters.

**Comment by mkborregaard** [comment]
The semicolon and slash aren't part of the Danish keyboard, those are occupied by other letters (æ, ø and å). In fact even the idea of "main section of keyboard" is subtly different: `-` is in the location of `/`, `æ` is in the location of `;`, `ø` is in the location of `'`, `å` is in the location of `[`. I think we could probably just set the missing frequencies at 0, given their very external, and fairly congruent, position on all layouts?

**Comment by stevep99** [comment]
OK, I have good news. I just updated the Keyboard Analyzer to 1.16, which allows selection of alternative letter-frequency data. You can load in the Danish frequencies referred to above by going to:

http://colemakmods.github.io/mod-dh/analyze.html?freq=da

Since there are no punctuation characters in the data, those these won't contribute to the scores. But you should at least be able to include the special Danish symbols to your layout :P

Poking around practicalcryptography.com site, I see that have frequency tables for other languages too, so I'll add more languages in the near future.

**Comment by mkborregaard** [comment]
That's awesome news, thanks so much for this! I can't wait with poking around. What if one layout turns out to be superior across all the latin-alphabet languages?! :-)

**Comment by mkborregaard** [comment]
Turns out Mod-DH is still best at a quick test, and the relative frequencies don't change much. Even though the Colemak layout is designed for English. That's super interesting (and gratifying, as a Mod-DH typist myself).

**Comment by mkborregaard** [comment]
Sorry to keep asking questions here, but is it correctly understood you don't calculate the frequency with which a bigram involves two contiguous fingers on the same hand? AFAIU Colemak is also designed to make this happen as frequently as possible - e.g. I love the feeling of writing "first".

**Comment by stevep99** [comment]
You are right, the model doesn't explicitly take into account nice bigrams such as ST and NE. But these are accounted for in one sense - the effort score for those keys is the minimal possible.

**Comment by DreymaR** [comment]
That gets slightly tricky, as the general feeling is that inward rolls are great, outward rolls acceptable and mixed in-out rolls not good. Quantifying these sentiments is bound to be conjectural.

**Comment by mkborregaard** [comment]
Still, I think those considerations are thought into the very design of Colemak, aren't they?
