### ISSUE TITLE
Which Angle mod is correct?

### ISSUE THREAD

**Issue by yg8ijvjvjv** [ColemakMods/mod-dh#35]
In https://colemakmods.github.io/mod-dh/keyboards.html, the following Angle mod is shown:
4 on the left middle, 6 on the left index, 8 on the right index
In DH-k and in https://colemakmods.github.io/mod-dh/analyze.html, the following is used:
4 on the left index, 6 on the right index, 8 on the right index
In the stevep fork of the keyboard layout analyzer in the presets, the following is used:
4 on the left middle, 6 on the left index, 8 on the right middle

Which Angle mod is correct?

**Comment by stevep99** [comment]
Well spotted. It's mainly because the DHk images are older, the newer images are intended more closely match DreymaR's. The 6 in particular is closer to T than N so logically it should be on the left. However some split keyboards - such as mine - have 6 on the right.

To be honest, for the number row, the images are just guide. It's largely up to user preference and I recommend people use whatever they find most comfortable.

**Comment by DreymaR** [comment]
Whether 3 and 4 are hit by the left ring, middle or index fingers isn't as much a matter of the Angle mod (no keys are moved) as of personal preference. I sometimes call that an "eD fingering scheme". Basically, just use what you feel like for those numbers, and the same for 9 and 0. In my help images I've colored the 3 and 9 keys with gradients to show the fuzziness of fingering.

6 on left or right index is, as Steve says, not a matter of Angle mod either but of the Wide mod vs your hardware. The difference is not between split and single-slab boards though, but between row-staggered and matrix-type boards. The latter have 6 on the right, the former on the left – even when split. Since these images are row-staggered, they should therefore have the 6 on the left.

**Comment by yg8ijvjvjv** [comment]
I think it is a matter of the Angle mod, because in the typist used to the standard stagger, the fingers would naturally continue to move to the number row with the stagger and not against the stagger, however with the Angle mod the fingers instead naturally move outwards.
