### ISSUE TITLE
Can we add the "Caps Lock as Backspace" shinanigan?

### ISSUE THREAD

**Issue by MarinaniYT** [ColemakMods/mod-dh#36]
I use the regular Colemak keyboard, but with Caps Lock as Backspace. But I saw this mod and got interested, but a bit disappointed when I couldn't find a version that had the Caps Lock as Backspace. So can we please have this version?
P.S. I have created this keyboard, so if we can just slip it into the repo?

**Comment by DreymaR** [comment]
Just... Extend is like, so very very much better!  ( のvの) c[_]

**Comment by stevep99** [comment]
The difficulty is that people have a wide variety of preferences for the Caps Lock key. Some leave it unchanged, some set it to backspace, some to Control, some to the Win/Gui key, and yet others use it as a special modifier (e.g. Extend) as DreymaR mentions). 

For this reason, I prefer not specify what CapsLock should be in the base layout, and let people configure it as they see fit.

**Comment by MattKang** [comment]
I disagree with this decision. Caps as Backspace isn't just some arbitrary preference but rather something defined by the original Colemak standard. Shouldn't require someone to have to download and use KLC to get this going. One more layout seems quite reasonable to maintain given the code frequency of this repo.

**Comment by DreymaR** [comment]
I strongly agree with this decision. Modularity is king!

While Shai created a truly brilliant layout design in the Colemak layout, packaging Caps as Backspace with it instead of keeping it as an option as it should be was a poor decision. In Linux there are keyboard options for Capslock key behavior, and several of the Colemak layout implementations that try to force this package down the throat of the OS break proper protocol in their enthusiasm, with confusing and problematic results.

I also promote modularity in ergonomic mods, as shown in my BigBag. Ideally, users should be able to choose a combination of mods and additions that suits them, pretty much regardless of what their main layout is. Of course, not all optimized layouts make this possible.

Don't get me started on Shai's AltGr layers, another part of the package that I'd really like to see presented as an option. In this case, OSes aren't designed for full modularity although Linux XKB kind of sort of semi-supports it. But conceptually, there isn't really much of a necessary connection between your main/Shift, AltGr/symbol and Extend or other layers.

**Comment by MattKang** [comment]
>In Linux there are keyboard options for Capslock key behavior, and several of the Colemak layout implementations that try to force this package down the throat of the OS break proper protocol in their enthusiasm, with confusing and problematic results.

Not in Windows.

> Once you factor in all possible beneficial mod combinations, it is no longer "one more layout" but lots and lots.

That's a slippery slope fallacy.

It sounds like a lot of your objections revolve around perceived flaws in the original layout. To be fair, that's why this mod exists in the first place. However, I think it's reasonable to have a standard Colemak layout available with *just* the DH mod. Allow others to continue to modify as they please.

**Comment by MattKang** [comment]
I'll also add that, as a Colemak user for many years, the lack of a "default" layout here has been enough to make me question whether I want to try the DH mod outright. I'm using the one with caps lock enabled, and it's really throwing me off. Ultimately, I would hope this repo exists to promote adoption. Even amongst old vanilla users like myself.

**Comment by DreymaR** [comment]
In Windows it hasn't been much better, I can assure you. The MSKLC tool doesn't really support making the Caps key into a Backspace, and implementations have been hacky and sometimes led to grave technical problems. The one we use now works decently but it's still a hack, abusing the key enumeration table. Microsoft would not be happy. So yes, the default MS implementation of the Caps-to-Back mapping is also problematic. AHK and similar scripts work well enough in that respect, but have other problems. And registry remappings are rather dramatic.

I think you misinterpret me when calling me out for slippery slope. I said beneficial, and I do mean quite strongly that I could list several mods that are many times better than the caps-to-back remap! Extend alone is so much better that I can't begin to describe it although I guess you don't see its strengths. And I'd take the Angle or even Wide mod over caps-to-back given a choice. So it's not the slippery slope, it's the reality of your preferred mod not being the best choice to a lot of people.

The flaws I list are not in the original layout but in its bundling policy. The Colemak layout is a great layout, whether bundled with AltGr layers and Caps-to-Back remappings or not. In today's alt-layout environment such bundlings still occur but modularity is generally much more common. Layout is one thing, layers another. The bundling policy is a totally different matter from the considerations that led to the DH mod.
