### ISSUE TITLE
Layout Analysis Tool not accepting custom traditional layouts

### ISSUE THREAD

**Issue by binarybottle** [ColemakMods/mod-dh#38]
I can't seem to analyze custom layouts like the following on https://colemakmods.github.io/mod-dh/analyze.html

Hieamtsrn:

1  2  3  4  5  6  7  8  9  0  (  )
b  y  o  u  '  k  d  c  l  p  q  =
h  i  e  a  ,  m  t  s  r  n  v
x  -  "  .  ?  w  g  f  j  z

**Comment by stevep99** [comment]
I think the problem here is that by default, the analyzer assumes the standard shifted character for each of the symbols keys. 

So for example, where you have ( ), there are effectively two sets of brackets because 9 and 0 will also have brackets in Layer 2.

You can fix this by supplying shifted versions of all your symbols, like this:
```
1[ 2] 3  4$ 5% 6^ 7& 8* 9< 0> ({ )}
b  y  o  u  '@ k  d  c  l  p  q =+
h  i  e  a  ,; m  t  s  r  n  v
x  -_ "/ .: ?! w  g  f  j  z

```
The # character is a comment so you can't use that also :)

**Comment by binarybottle** [comment]
Thank you very much, @stevep99 !
